spring.application.name=ei-dashboard
server.port=${SERVER_PORT:8081}
server.servlet.context-path=/ei-dashboard

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/extra_income_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:extra_income_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true

spring.liquibase.change-log= classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled= true
spring.liquibase.database-change-log-table= dashboard_databasechangelog
spring.liquibase.database-change-log-lock-table= dashboard_databasechangeloglock

jwt.secret=${JWT_SECRET:adminjwtsecretkey123456789}
jwt.expirationMs=${JWT_EXPIRATION_MS:3600000}
