spring.application.name=ei-dashboard
server.port=8081
server.servlet.context-path=/ei-dashboard

spring.datasource.url=jdbc:postgresql://localhost:5432/ei_dashboard_db
spring.datasource.username= postgres
spring.datasource.password= postgres

spring.jpa.hibernate.ddl-auto= create
spring.jpa.show-sql= true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true

spring.liquibase.change-log= classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled= true

jwt.secret= adminjwtsecretkey123456789
jwt.expirationMs= 3600000
